# Generated by Django 2.2.13 on 2020-12-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_remove_bond_maturity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
