# Generated by Django 2.2.13 on 2020-12-12 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0004_auto_20201212_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='maturity',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bond',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
